Feature
Chancellor-Arthur/cv-map-timer-react pull request #1
Opened 2022-07-12 10:29 UTC by Chancellor-Arthur

2022-07-19 19:03 UTC, crutch12 commented
отдал @stilwuc

2022-07-22 11:46 UTC, Chancellor-Arthur commented
Внес некоторые последние правки, залил на heroku, рекомендую смотреть сайт там, github-pages работают странно и не предсказуемо

2022-07-26 07:34 UTC, Stilwuc requested changes
В целом гуд. К функциональной части нету вопросов, все работает по тз.
По коду чутка поправить надо)

2022-07-26 07:34 UTC, Stilwuc commented on src/App.js
> +import "./styles/App.css";
У тебя там пустой файл, можно удалить

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/CV.jsx
> +export default Cv;
Тоже небольшая дестабилизация названий)
Обычно название файла = название компонента, у тебя отличается кейс
Но при импорте у тебя кейсовка уже по названию файла)
Вообщем аккуратно тут, и лучше приводить к одному виду (`Cv` мне нравится больше, аббревиатуры я обычно не разделяю кейсом)

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/CV.jsx
> +                         style={{width: '100%'}}/>
ну width: 100% есть в bootstrap, лучше  тогда юзать их классы раз подключил

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/CV.jsx
> +                                src="https://i.ibb.co/3vK37KJ/5ded53183a22616ee70c96ae.png" alt=""
Картинки-ссылки на сторонние ресурсы допустимы, но всегда лучше юзать свои, а то сторонние ресурсы нестабильные и могут не работать

2022-07-26 07:34 UTC, Stilwuc commented on src/index.js
> -  <React.StrictMode>
`StrictMode` лучше оставить, так как он может помочь поймать пару косяков

2022-07-26 07:34 UTC, Stilwuc commented on src/styles/Timer.css
> +    font-size: 300%;
Прикольно)
Но обычно `font-size` задают `px/rem/em/pt`

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/Timer.jsx
> +    const $hours = useRef();
`$..` jQuery история, мы такое не юзаем при именовании ref)
Да и вообще ref нужно юзать когда тебе прям очень сильно нужен доступ к dom элементу и ты по другому не можешь. В твоем случае можешь, используй обычный `useState` и отображай его значение в верстке.

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/Timer.jsx
> +        const minutes = Math.floor(timer / 60) % 60;
Сложное форматирование, чтобы его прочитать нужно напрячься, что не есть хорошо.
Советую заюзать либы которое уже это делают.
Посмотри `date-fns` или `moment`

2022-07-26 07:34 UTC, Stilwuc commented on src/pages/Timer.jsx
> +        $hours.current.dataset.title = declensionNum(hours, ['час', 'часа', 'часов']);
Тоже есть либы которое работают с окончаниями, - `ru-plural` например

2022-07-26 13:39 UTC, Chancellor-Arthur commented on .gitignore
> -# production
Это не я, правда)

2022-07-26 13:41 UTC, Chancellor-Arthur commented on src/pages/MapDefault.jsx
> +const MapDefault = () => {
Default - потому что Map занято в яндекс-картах, а фантазии, на что-то удачное, не хватило

2022-07-26 13:46 UTC, Chancellor-Arthur commented on src/pages/Timer.jsx
> +        const minutes = Math.floor(timer / 60) % 60;
Окей, я просто думал, что само задание подразумевало написание полностью своего таймера, без доп библиотек, силами чистого js

2022-07-26 13:52 UTC, Stilwuc commented on docs/asset-manifest.json
> +{
Понял)
ну тогда раз ты от pages ушел то давай выпилим

2022-07-26 13:54 UTC, Stilwuc commented on src/pages/MapDefault.jsx
> +const MapDefault = () => {
Ты можешь всегда переопределить название компонента при импорте, например сделать импорт из яндекса
```
import {Map as YandexMap, Placemark, YMaps} from 'react-yandex-maps';
```
Ну и тогда фри название есть

2022-07-26 13:55 UTC, Stilwuc commented on src/pages/Timer.jsx
> +        const minutes = Math.floor(timer / 60) % 60;
Да не, жестко слишком
Мы все таки фронтендеры, и когда есть либа которая делает за тебя все что нужно, она уже считай подключена :D

2022-07-26 13:58 UTC, Chancellor-Arthur commented on docs/asset-manifest.json
> +{
Окей, сделаю

2022-07-26 14:00 UTC, Chancellor-Arthur commented
В скором времени всё исправлю

2022-07-26 18:42 UTC, crutch12 commented on src/pages/Timer.jsx
> +        $hours.current.dataset.title = declensionNum(hours, ['час', 'часа', 'часов']);
ru-plural согласен :)

2022-07-26 19:41 UTC, Stilwuc commented on src/pages/Timer.jsx
> +        const minutes = Math.floor(timer / 60) % 60;
Тут как скажешь :)

2022-07-30 19:41 UTC, Chancellor-Arthur commented
@Stilwuc, всё готово

2022-08-01 13:18 UTC, Stilwuc reviewed
Поправь плз querySelector'ы, и я апрувлю.
Не могу на них смотреть)

2022-08-01 13:18 UTC, Stilwuc commented on src/pages/Timer.jsx
> +        document.querySelector('.timer__seconds').dataset.title = plural(seconds, "секунда", "секунды", "секунд");
Не сильно нравится юзать querySelector'ы для того чтобы положить data атрибут и вывести саб тайтлы, тем более что правильней где можно юзать ref вместо document селекторов.
Но вообще тут более правильней вычилсять в runtime и в jsx вставлять единицу измерения с нужным окончаниям. Типо например такого
```
<div className="timer__item timer__hours" style={{ display: flex, flexDirection: 'column' }}>
  <span>{hours}</span>
  <span>{plural(hours, 'час', 'часа', 'часов')}</span>
</div>
```

2022-08-01 15:51 UTC, Chancellor-Arthur commented
@Stilwuc, поправил

2022-08-01 17:05 UTC, Stilwuc approved these changes
Лучший, можешь мержить 👍

2022-08-01 17:07 UTC, merged